-- Tabella Seasons
CREATE TABLE IF NOT EXISTS `seasons` (
  `year` INT PRIMARY KEY,
  `last_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
