-- Tabella Countries
CREATE TABLE IF NOT EXISTS `countries` (
  `name` VARCHAR(100) PRIMARY KEY,
  `code` VARCHAR(10),
  `flag` VARCHAR(255),
  `last_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
